version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/Django-code

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/Django-code/scripts
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu

